import { useQuery } from '@tanstack/react-query'
import { useTranslation } from 'react-i18next'
import { getWeeklySummary, getAnomalies } from '@/api/ai'

function pct(v: number | string | null) {
  if (v === null || v === undefined) return null
  const n = parseFloat(String(v))
  if (isNaN(n)) return null
  const sign = n >= 0 ? '+' : ''
  return `${sign}${n.toFixed(1)}%`
}

function StatCard({ label, value, sub, color = '#7c3aed' }: { label: string; value: string; sub?: string; color?: string }) {
  return (
    <div style={{ background: '#fff', border: '1px solid #e9e9ef', borderRadius: 14, padding: '18px 22px', flex: 1, minWidth: 160 }}>
      <p style={{ fontSize: 11, fontWeight: 700, color: '#9090a0', textTransform: 'uppercase', letterSpacing: '0.8px', marginBottom: 6 }}>{label}</p>
      <p style={{ fontSize: 26, fontWeight: 900, color, marginBottom: sub ? 4 : 0 }}>{value}</p>
      {sub && <p style={{ fontSize: 12, color: '#9090a0' }}>{sub}</p>}
    </div>
  )
}

export default function AiInsightsScreen() {
  const { i18n } = useTranslation()
  const isNl = i18n.language === 'nl'

  const { data: summary, isLoading: summaryLoading } = useQuery({
    queryKey: ['ai-weekly-summary'],
    queryFn: getWeeklySummary,
    staleTime: 1000 * 60 * 10,
  })

  const { data: anomalies = [], isLoading: anomLoading } = useQuery({
    queryKey: ['ai-anomalies'],
    queryFn: () => getAnomalies(30),
    staleTime: 1000 * 60 * 5,
  })

  const stats = summary?.stats

  return (
    <div style={{ padding: '32px 36px', maxWidth: 1100 }}>
      {/* Header */}
      <div style={{ marginBottom: 28 }}>
        <h1 style={{ fontSize: 26, fontWeight: 900, color: '#1c1c2e', letterSpacing: '-0.5px', marginBottom: 4 }}>
          {isNl ? 'AI-inzichten' : 'AI Insights'}
        </h1>
        <p style={{ fontSize: 14, color: '#6b7280' }}>
          {isNl ? 'Wekelijkse samenvatting, fraudewaarschuwingen en verkooptrends gegenereerd door AI.' : 'Weekly sales summary, fraud alerts and sales trends generated by AI.'}
        </p>
      </div>

      {/* Weekly summary */}
      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontSize: 16, fontWeight: 800, color: '#1c1c2e', marginBottom: 16 }}>
          📊 {isNl ? 'Wekelijkse samenvatting' : 'Weekly Summary'}
          {summary?.generated_at && (
            <span style={{ fontSize: 12, fontWeight: 400, color: '#9090a0', marginLeft: 10 }}>
              {isNl ? 'Gegenereerd:' : 'Generated:'} {new Date(summary.generated_at).toLocaleDateString(isNl ? 'nl-NL' : 'en-US')}
            </span>
          )}
        </h2>

        {summaryLoading ? (
          <div style={{ height: 120, background: '#f8f7ff', borderRadius: 14, border: '1px solid #ede9fe', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <div style={{ width: 28, height: 28, borderRadius: '50%', border: '3px solid #ede9fe', borderTopColor: '#7c3aed', animation: 'spin 0.8s linear infinite' }} />
          </div>
        ) : !summary ? (
          <div style={{ background: '#f8f7ff', border: '1px dashed #c4b5fd', borderRadius: 14, padding: '32px 24px', textAlign: 'center' }}>
            <p style={{ fontSize: 15, fontWeight: 700, color: '#7c3aed', marginBottom: 6 }}>
              {isNl ? 'Nog geen samenvatting beschikbaar' : 'No summary available yet'}
            </p>
            <p style={{ fontSize: 13, color: '#9090a0' }}>
              {isNl ? 'De wekelijkse samenvatting wordt elke maandag gegenereerd.' : 'The weekly summary is generated every Monday morning.'}
            </p>
          </div>
        ) : (
          <>
            {/* Stats row */}
            {stats && (
              <div style={{ display: 'flex', gap: 14, marginBottom: 20, flexWrap: 'wrap' }}>
                <StatCard
                  label={isNl ? 'Omzet deze week' : 'Revenue this week'}
                  value={`SRD ${parseFloat(String(stats.this_week.total_srd)).toFixed(2)}`}
                  sub={pct(stats.revenue_change_pct) ? `${pct(stats.revenue_change_pct)} ${isNl ? 't.o.v. vorige week' : 'vs last week'}` : undefined}
                  color={stats.revenue_change_pct !== null && parseFloat(String(stats.revenue_change_pct)) >= 0 ? '#16a34a' : '#dc2626'}
                />
                <StatCard
                  label={isNl ? 'Transacties' : 'Transactions'}
                  value={String(stats.this_week.count)}
                  sub={pct(stats.transaction_change_pct) ? `${pct(stats.transaction_change_pct)} ${isNl ? 't.o.v. vorige week' : 'vs last week'}` : undefined}
                  color='#1d4ed8'
                />
                <StatCard
                  label={isNl ? 'Gem. bonbedrag' : 'Avg. basket'}
                  value={`SRD ${parseFloat(String(stats.this_week.avg_basket)).toFixed(2)}`}
                  color='#7c3aed'
                />
                {stats.this_week.void_count > 0 && (
                  <StatCard
                    label={isNl ? 'Annuleringen' : 'Voids'}
                    value={String(stats.this_week.void_count)}
                    color='#dc2626'
                  />
                )}
              </div>
            )}

            {/* AI narrative */}
            {summary.narrative && (
              <div style={{ background: 'linear-gradient(135deg,#f8f7ff,#eff6ff)', border: '1px solid #e0e7ff', borderRadius: 14, padding: '20px 24px', display: 'flex', gap: 14 }}>
                <div style={{ width: 36, height: 36, borderRadius: 10, background: 'linear-gradient(135deg,#7c3aed,#4f46e5)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 18, flexShrink: 0 }}>
                  🤖
                </div>
                <div>
                  <p style={{ margin: '0 0 4px', fontSize: 12, fontWeight: 700, color: '#7c3aed', textTransform: 'uppercase', letterSpacing: '0.6px' }}>
                    AI {isNl ? 'Analyse' : 'Analysis'}
                  </p>
                  <p style={{ margin: 0, fontSize: 14, color: '#374151', lineHeight: 1.6 }}>{summary.narrative}</p>
                </div>
              </div>
            )}

            {/* Top products */}
            {stats?.top_products && stats.top_products.length > 0 && (
              <div style={{ marginTop: 20 }}>
                <p style={{ fontSize: 13, fontWeight: 700, color: '#6b7280', marginBottom: 10 }}>
                  {isNl ? 'Top producten deze week' : 'Top products this week'}
                </p>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                  {stats.top_products.slice(0, 5).map((p, i) => (
                    <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '10px 16px', background: '#fff', borderRadius: 10, border: '1px solid #f3f3f8' }}>
                      <span style={{ width: 24, height: 24, borderRadius: 6, background: '#7c3aed', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 12, fontWeight: 800, flexShrink: 0 }}>
                        {i + 1}
                      </span>
                      <span style={{ flex: 1, fontSize: 13, fontWeight: 600, color: '#1c1c2e' }}>{p.name}</span>
                      <span style={{ fontSize: 12, color: '#6b7280' }}>{p.qty}x</span>
                      <span style={{ fontSize: 13, fontWeight: 700, color: '#16a34a' }}>SRD {parseFloat(String(p.revenue)).toFixed(2)}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </>
        )}
      </section>

      {/* Anomaly / fraud alerts */}
      <section>
        <h2 style={{ fontSize: 16, fontWeight: 800, color: '#1c1c2e', marginBottom: 16 }}>
          🚨 {isNl ? 'Fraudewaarschuwingen (30 dagen)' : 'Fraud Alerts (30 days)'}
          {anomalies.length > 0 && (
            <span style={{ marginLeft: 10, padding: '2px 10px', borderRadius: 12, background: '#fef2f2', border: '1px solid #fecaca', fontSize: 12, fontWeight: 700, color: '#dc2626' }}>
              {anomalies.length}
            </span>
          )}
        </h2>

        {anomLoading ? (
          <div style={{ height: 80, background: '#fff', borderRadius: 14, border: '1px solid #e9e9ef', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <div style={{ width: 24, height: 24, borderRadius: '50%', border: '3px solid #f3f3f3', borderTopColor: '#dc2626', animation: 'spin 0.8s linear infinite' }} />
          </div>
        ) : anomalies.length === 0 ? (
          <div style={{ background: '#f0fdf4', border: '1px solid #bbf7d0', borderRadius: 14, padding: '28px 24px', textAlign: 'center' }}>
            <p style={{ fontSize: 24, marginBottom: 8 }}>✅</p>
            <p style={{ fontSize: 14, fontWeight: 700, color: '#15803d' }}>
              {isNl ? 'Geen afwijkingen gedetecteerd' : 'No anomalies detected'}
            </p>
            <p style={{ fontSize: 13, color: '#16a34a' }}>
              {isNl ? 'De afgelopen 30 dagen zijn er geen verdachte transacties gevonden.' : 'No suspicious transactions found in the last 30 days.'}
            </p>
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {anomalies.map((a, i) => (
              <div key={i} style={{ background: '#fff', border: '1px solid #fecaca', borderLeft: '4px solid #dc2626', borderRadius: 12, padding: '16px 20px' }}>
                <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}>
                  <div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6, flexWrap: 'wrap' }}>
                      {a.sale_number && (
                        <span style={{ fontSize: 12, fontWeight: 700, color: '#dc2626', fontFamily: 'monospace', background: '#fef2f2', padding: '2px 8px', borderRadius: 6 }}>
                          #{a.sale_number}
                        </span>
                      )}
                      {a.flags.map((f, j) => (
                        <span key={j} style={{ fontSize: 11, fontWeight: 700, color: '#92400e', background: '#fffbeb', border: '1px solid #fde68a', padding: '2px 8px', borderRadius: 6 }}>
                          {f}
                        </span>
                      ))}
                    </div>
                    <div style={{ fontSize: 12, color: '#6b7280', display: 'flex', gap: 12, flexWrap: 'wrap' }}>
                      {a.store && <span>🏪 {a.store}</span>}
                      {a.cashier && <span>👤 {a.cashier}</span>}
                      {a.total_srd && <span>💰 SRD {parseFloat(a.total_srd).toFixed(2)}</span>}
                    </div>
                  </div>
                  <span style={{ fontSize: 11, color: '#9090a0', whiteSpace: 'nowrap' }}>
                    {new Date(a.detected_at).toLocaleDateString(isNl ? 'nl-NL' : 'en-US', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}
                  </span>
                </div>
                {a.ai_narrative && (
                  <p style={{ margin: '10px 0 0', fontSize: 13, color: '#374151', lineHeight: 1.5, paddingTop: 10, borderTop: '1px solid #fecaca' }}>
                    🤖 {a.ai_narrative}
                  </p>
                )}
              </div>
            ))}
          </div>
        )}
      </section>
    </div>
  )
}
