<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Postgres represents Laravel's `enum` as a TEXT column with a CHECK constraint.
 * Adding a new role to the App\Models\User::ROLES array isn't enough — the DB
 * still rejects the new value. This migration relaxes the constraint to allow
 * the new `tax_inspector` role (Belastingdienst Suriname tax officer, added
 * with the BTW Submissions workflow).
 *
 * We can't easily ALTER an enum constraint in place, so we drop and recreate
 * it. The set of valid roles is a superset of the previous list.
 */
return new class extends Migration {
    public function up(): void
    {
        // Drop the existing constraint (name is auto-generated by Laravel/Postgres).
        DB::statement('ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check');

        // Recreate it with the full set of roles, including tax_inspector.
        DB::statement(<<<'SQL'
            ALTER TABLE users
            ADD CONSTRAINT users_role_check
            CHECK (role IN (
                'super_admin',
                'organisation_admin',
                'store_manager',
                'cashier',
                'auditor',
                'api_integration',
                'tax_inspector'
            ))
        SQL);
    }

    public function down(): void
    {
        // Reject any tax_inspector rows that exist before we tighten the
        // constraint back (otherwise the new check would fail to apply).
        DB::table('users')->where('role', 'tax_inspector')->delete();

        DB::statement('ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check');

        DB::statement(<<<'SQL'
            ALTER TABLE users
            ADD CONSTRAINT users_role_check
            CHECK (role IN (
                'super_admin',
                'organisation_admin',
                'store_manager',
                'cashier',
                'auditor',
                'api_integration'
            ))
        SQL);
    }
};
