<!DOCTYPE html>
<html lang="{{ $locale }}">
<head>
<meta charset="UTF-8">
<style>
  body  { font-family: Arial, sans-serif; font-size: 12px; color: #222; margin: 30px; }
  h1    { font-size: 20px; color: #1a5276; margin-bottom: 4px; }
  h2    { font-size: 14px; color: #555; margin: 20px 0 8px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  th    { background: #1a5276; color: #fff; padding: 6px 8px; text-align: left; font-size: 11px; }
  td    { padding: 5px 8px; border-bottom: 1px solid #eee; }
  .right  { text-align: right; }
  .total  { font-weight: bold; background: #eaf0fb; }
  .exempt { color: #888; font-style: italic; }
  .footer { margin-top: 30px; font-size: 10px; color: #aaa; border-top: 1px solid #eee; padding-top: 8px; }
  .stamp  { display: inline-block; border: 2px solid #1a5276; color: #1a5276; padding: 3px 10px; border-radius: 4px; font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; }
</style>
</head>
<body>

<table style="width:100%; border:none; margin-bottom:20px">
  <tr>
    <td style="border:none; padding:0">
      <h1 style="margin:0">
        @if($locale === 'nl')BTW-Aangifte Overzicht @else BTW Declaration Summary @endif
      </h1>
      <p style="color:#888; font-size:11px; margin:4px 0 0">
        @if($locale === 'nl')Periode:@else Period:@endif
        {{ $data['date_from'] }} @if($locale === 'nl')t/m @else to @endif {{ $data['date_to'] }}
        &nbsp;|&nbsp;
        @if($locale === 'nl')Gegenereerd op:@else Generated:@endif
        {{ now()->setTimezone('America/Paramaribo')->format('d-m-Y H:i') }} AST
      </p>
    </td>
    <td style="border:none; padding:0; text-align:right; vertical-align:top">
      <span class="stamp">Belastingdienst Suriname</span>
      <p style="font-size:10px; color:#aaa; margin:4px 0 0">Josbin POS</p>
    </td>
  </tr>
</table>

{{-- ── BTW breakdown by rate ── --}}
<h2>
  @if($locale === 'nl')BTW-overzicht per tarief @else BTW breakdown by rate @endif
</h2>
<table>
  <tr>
    <th>@if($locale === 'nl')BTW-tarief @else BTW rate @endif</th>
    <th class="right">@if($locale === 'nl')Bruto incl. BTW @else Gross incl. BTW @endif (SRD)</th>
    <th class="right">@if($locale === 'nl')Netto excl. BTW @else Net excl. BTW @endif (SRD)</th>
    <th class="right">@if($locale === 'nl')BTW-bedrag @else BTW amount @endif (SRD)</th>
    <th class="right">@if($locale === 'nl')Transacties @else Transactions @endif</th>
  </tr>
  @foreach($data['breakdown'] as $row)
  <tr @if($row->btw_exempt) class="exempt" @endif>
    <td>
      @if($row->btw_exempt)
        @if($locale === 'nl')Vrijgesteld (0%)@else Exempt (0%)@endif
      @else
        {{ number_format((float)$row->btw_rate, 0) }}%
      @endif
    </td>
    <td class="right">{{ number_format((float)$row->gross_incl_btw, 2, '.', ',') }}</td>
    <td class="right">{{ number_format((float)$row->net_excl_btw, 2, '.', ',') }}</td>
    <td class="right">
      @if($row->btw_exempt)—
      @else{{ number_format((float)$row->btw_amount, 2, '.', ',') }}
      @endif
    </td>
    <td class="right">{{ number_format($row->sale_count) }}</td>
  </tr>
  @endforeach
  <tr class="total">
    <td>@if($locale === 'nl')TOTAAL @else TOTAL @endif</td>
    <td class="right">SRD {{ number_format((float)$data['total_gross'], 2, '.', ',') }}</td>
    <td class="right">—</td>
    <td class="right">SRD {{ number_format((float)$data['total_btw'], 2, '.', ',') }}</td>
    <td class="right">—</td>
  </tr>
</table>

{{-- ── Declaration note ── --}}
<p style="font-size:11px; color:#555; background:#f5f5f5; padding:10px 14px; border-radius:4px; border-left:3px solid #1a5276">
  @if($locale === 'nl')
    Dit overzicht is gegenereerd door Josbin POS en geeft de BTW-verdeling weer over de geselecteerde periode.
    Te gebruiken als bijlage bij de BTW-aangifte bij de Belastingdienst Suriname.
  @else
    This summary was generated by Josbin POS and shows the BTW distribution for the selected period.
    Use as attachment with the BTW declaration to Belastingdienst Suriname.
  @endif
</p>

<div class="footer">
  Josbin POS &copy; {{ date('Y') }} &nbsp;&middot;&nbsp;
  @if($locale === 'nl')Betrouwbaar kassasysteem voor Suriname @else Reliable POS for Suriname @endif
  &nbsp;&middot;&nbsp; AST (UTC&minus;3)
  &nbsp;&middot;&nbsp; WBP-S compliant
</div>
</body>
</html>
